# Auto-generated Terraform — ttt
# Generated by AI Infrastructure Agent

terraform {
  required_version = ">= 1.5.0"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }

  backend "s3" {
    bucket         = "ttt-tf-state"
    key            = "ttt/terraform.tfstate"
    region         = "ap-south-1"
    dynamodb_table = "ttt-tf-lock"
  }
}

provider "aws" {
  region = "ap-south-1"

  default_tags {
    tags = {
      Project   = "ttt"
      ManagedBy = "terraform"
    }
  }
}






# ── S3 ────────────────────────────────────────────────────────────
resource "random_id" "suffix" {
  byte_length = 4
}

resource "aws_s3_bucket" "app_bucket" {
  bucket = "ttt-storage-${random_id.suffix.hex}"
  tags   = { Name = "ttt-bucket" }
}

resource "aws_s3_bucket_versioning" "versioning" {
  bucket = aws_s3_bucket.app_bucket.id
  versioning_configuration {
    status = "Enabled"
  }
}

output "s3_bucket_name" {
  value       = aws_s3_bucket.app_bucket.bucket
  description = "Name of the S3 bucket"
}










